apiVersion: artifact.falcosecurity.dev/v1alpha1
kind: Config
metadata:
  name: config-test
spec:
  config: |
    json_output: true
    json_include_output_property: true
    log_stderr: true
    log_syslog: false
    log_level: info
