apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco-operator-rolebinding
  labels:
    app.kubernetes.io/name: "falco-operator"
    app.kubernetes.io/instance: "falco-operator"
    app.kubernetes.io/part-of: "falco"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: falco-operator-role
subjects:
  - kind: ServiceAccount
    name: falco-operator
    namespace: falco-operator
